abhaysamantni/PythonReview

class_register.txt
=> Added My Name to Register

class_register.txt
=> added my name

class_register.txt
Added first and last name to class_register.txt using the FirstName_LastName format
=> added my first and last name (Arjun_Patel)

class_register.txt
Added a new name to class_register.txt
=> class_register.txt added a new name

class_register.txt
=> Added Name

class_register.txt
Apologies for the late submission I was away from my laptop until now.
=> I added my name and hobbies

class_register.txt
Changed my initials and changed my hobby
=> added initials and hobby

class_register.txt
Updated my initials and interest and am submitting this pull request. Thanks.
=> Initials SG updated

class_register.txt
=> modified class register file

class_register.txt
Hello, here is the requested information for today's class activity!
1/12/2023
~Jason Zubia
=> Typed in my information into class_register

class_register.txt
=> first commit

class_register.txt
I just finished edited register file
=> finished edited register file

class_register.txt
=> Added Jasper Register Changes

class_register.txt
=> Committing initials

class_register.txt
Followed instructions and edited last line w initials and hobby
=> Commit message

class_register.txt
Completion of in-class exercise.
=> Added line for Paul Bessler

class_register.txt
Pull Request for additional line in text file.
=> SS Submission

class_register.txt
Attempt at creating pull request for class_register.txt line addition.
=> Updated line in class_register.txt

class_register.txt
=> Alexander Sabolcik inclass 1

class_register.txt
=> APAD_homework_abhiramiyengar

class_register.txt
=> Name Addition

class_register.txt
=> Pull request

class_register.txt
In Class Exercise One - Richard Bai
=> Richard InclassExercise1
